namespace XSVim

[<AutoOpen>]
module mapping =
    let (|KeyPressColemak|_|) = function
        | "f" -> Some "e"
        | "p" -> Some "r"
        | "g" -> Some "t"
        | "j" -> Some "y"
        | "l" -> Some "u"
        | "u" -> Some "i"
        | "y" -> Some "o"
        | ";" -> Some "p"
        | "r" -> Some "s"
        | "s" -> Some "d"
        | "t" -> Some "f"
        | "d" -> Some "g"
        | "n" -> Some "j"
        | "e" -> Some "k"
        | "i" -> Some "l"
        | "o" -> Some ";"
        | "k" -> Some "n"
        | "F" -> Some "E"
        | "P" -> Some "R"
        | "G" -> Some "T"
        | "J" -> Some "Y"
        | "L" -> Some "U"
        | "U" -> Some "I"
        | "Y" -> Some "O"
        | ":" -> Some "P"
        | "R" -> Some "S"
        | "S" -> Some "D"
        | "T" -> Some "F"
        | "D" -> Some "G"
        | "N" -> Some "J"
        | "E" -> Some "K"
        | "I" -> Some "L"
        | "O" -> Some ":"
        | "K" -> Some "N"
        | c -> Some c

    let (|KeyPressDvorark|_|) = function
        | "[" -> Some "-"
        | "]" -> Some "="
        | "'" -> Some "q"
        | "," -> Some "w"
        | "." -> Some "e"
        | "p" -> Some "r"
        | "y" -> Some "t"
        | "f" -> Some "y"
        | "g" -> Some "u"
        | "c" -> Some "i"
        | "r" -> Some "o"
        | "l" -> Some "p"
        | "/" -> Some "["
        | "=" -> Some "]"
        | "o" -> Some "s"
        | "e" -> Some "d"
        | "u" -> Some "f"
        | "i" -> Some "g"
        | "d" -> Some "h"
        | "h" -> Some "j"
        | "t" -> Some "k"
        | "n" -> Some "l"
        | "s" -> Some ";"
        | "-" -> Some "'"
        | ";" -> Some "z"
        | "q" -> Some "x"
        | "j" -> Some "c"
        | "k" -> Some "v"
        | "x" -> Some "b"
        | "b" -> Some "n"
        | "w" -> Some ","
        | "v" -> Some "."
        | "z" -> Some "/"
        | "{" -> Some "_"
        | "}" -> Some "+"
        | "\"" -> Some "Q"
        | "<" -> Some "W"
        | ">" -> Some "E"
        | "P" -> Some "R"
        | "Y" -> Some "T"
        | "F" -> Some "Y"
        | "G" -> Some "U"
        | "C" -> Some "I"
        | "R" -> Some "O"
        | "L" -> Some "P"
        | "?" -> Some "{"
        | "+" -> Some "}"
        | "O" -> Some "S"
        | "E" -> Some "D"
        | "U" -> Some "F"
        | "I" -> Some "G"
        | "D" -> Some "H"
        | "H" -> Some "J"
        | "T" -> Some "K"
        | "N" -> Some "L"
        | "S" -> Some ":"
        | "_" -> Some "\""
        | ":" -> Some "Z"
        | "Q" -> Some "X"
        | "J" -> Some "C"
        | "K" -> Some "V"
        | "X" -> Some "B"
        | "B" -> Some "N"
        | "M" -> Some "M"
        | "W" -> Some "<"
        | "V" -> Some ">"
        | "Z" -> Some "?"
        | c -> Some c

    let remap layout key =
        match layout, key with
        | Colemak, KeyPressColemak c -> c
        | Dvorak, KeyPressDvorark c -> c
        | _, c -> c
